version: '3'
services:
  sj-core-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: sj-core-api
    restart: always
    ports:
      - 3200:3200
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - SJ-MYSQL-CORE
    networks:
      - SJ-NETWORK-CORE  
       
  SJ-MYSQL-CORE:
    image: mysql:8
    container_name: SJ-MYSQL-CORE
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_NAME: mysql
    ports:
      - 3387:3306
    volumes:
      - SJ-MYSQL-CORE:/var/lib/mysql
    networks:
      - SJ-NETWORK-CORE

volumes:
  SJ-MYSQL-CORE:

networks:
  SJ-NETWORK-CORE:
