version: '3'
services:
  core-sepasang-stg:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: core-sepasang-stg
    restart: always
    ports:
      - ${APP_PORT_EXT}:${APP_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - SJ-NETWORK-CORE  

networks:
  SJ-NETWORK-CORE:
