version: '3'
services:
  core-sepasang:
    image: ${DOCKER_IMAGE}
    container_name: core-sepasang-prod
    restart: always
    ports:
      - 3200:3200
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - SJ-NETWORK-CORE  

networks:
  SJ-NETWORK-CORE:
