version: '3'
services:
  sp-mysql-dev:
    image: mysql:8
    container_name: sp-mysql-dev
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_NAME: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - sp-mysql-core:/var/lib/mysql
    networks:
      - SJ-NETWORK-CORE  

networks:
  SJ-NETWORK-CORE:

volumes:
  sp-mysql-core: