name: Build and Publish Sepasang Planner

on:
  push:
    tags:
      - '*'

env:
  GHRC_USER: ${{ secrets.GHRC_USER }}
  GHRC_PASS: ${{ secrets.GHRC_PASS }}
  REGISTRY: ghcr.io
  LATEST_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=$(echo "${{ github.ref }}" | sed -e 's,refs/tags/,,')
          docker build -t $REGISTRY/$REPO_NAME:$TAG_NAME -f prod.Dockerfile --build-arg TAG=$TAG_NAME .

      - name: Push Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=$(echo "${{ github.ref }}" | sed -e 's,refs/tags/,,')
          docker push $REGISTRY/$REPO_NAME:$TAG_NAME

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GHRC_USER }}
          password: ${{ env.GHRC_PASS }}

      - name: Update Latest Tag
        run: |
          docker pull ${{ env.REGISTRY }}/${{ github.repository | lower }}:${{ github.ref | replace('refs/tags/', '') }}
          docker tag ${{ env.REGISTRY }}/${{ github.repository | lower }}:${{ github.ref | replace('refs/tags/', '') }} ${{ env.REGISTRY }}/${{ github.repository | lower }}:${{ env.LATEST_TAG }}
          docker push ${{ env.REGISTRY }}/${{ github.repository | lower }}:${{ env.LATEST_TAG }}
