name: Build and Publish Sepasang Planner

on:
  push:
    tags:
      - '*'

env:
  GHRC_USER: ${{ secrets.GHRC_USER }}
  GHRC_PASS: ${{ secrets.GHRC_PASS }}
  REGISTRY: ghcr.io
  LATEST_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GHRC_USER }}
          password: ${{ env.GHRC_PASS }}

      - name: Build Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=$(echo "${{ github.ref }}" | sed -e 's,refs/tags/,,')
          docker build -t $REGISTRY/$REPO_NAME:$TAG_NAME -f prod.Dockerfile --build-arg TAG=$TAG_NAME .
          docker image ls
          docker push $REGISTRY/$REPO_NAME:$TAG_NAME
          docker image tag $REGISTRY/$REPO_NAME:$TAG_NAME $REGISTRY/$REPO_NAME:${{ env.LATEST_TAG }}
          docker push $REGISTRY/$REPO_NAME:${{ env.LATEST_TAG }}
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ env.GHRC_USER }} -p ${{ env.GHRC_PASS }}
            cd ${{ secrets.PATH }} && docker-compose -f docker-compose.prod.yml pull
            cd ${{ secrets.PATH }} && docker-compose -f docker-compose.prod.yml down
            cd ${{ secrets.PATH }} && docker-compose -f docker-compose.prod.yml up -d --build
    when: manual
